## Pandas

In [16]:
#Скачайте любой табличный датасет 

import pandas as pd

In [17]:
data = pd.read_csv('C:/Users/vkhur/Desktop/Buckkemp Datascience/data.csv')
data.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [18]:
#Загрузите данные и проанализируйте их (используя функции .info и .describe)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                11765 non-null  float64
 2   Item_Fat_Content           14204 non-null  object 
 3   Item_Visibility            14204 non-null  float64
 4   Item_Type                  14204 non-null  object 
 5   Item_MRP                   14204 non-null  float64
 6   Outlet_Identifier          14204 non-null  object 
 7   Outlet_Establishment_Year  14204 non-null  int64  
 8   Outlet_Size                10188 non-null  object 
 9   Outlet_Location_Type       14204 non-null  object 
 10  Outlet_Type                14204 non-null  object 
 11  Item_Outlet_Sales          14204 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.3+ MB


In [19]:
data.describe()

Item_Weight  Item_Visibility      Item_MRP  Outlet_Establishment_Year  \
count  11765.000000     14204.000000  14204.000000               14204.000000   
mean      12.792854         0.065953    141.004977                1997.830681   
std        4.652502         0.051459     62.086938                   8.371664   
min        4.555000         0.000000     31.290000                1985.000000   
25%        8.710000         0.027036     94.012000                1987.000000   
50%       12.600000         0.054021    142.247000                1999.000000   
75%       16.750000         0.094037    185.855600                2004.000000   
max       21.350000         0.328391    266.888400                2009.000000   

       Item_Outlet_Sales  
count       14204.000000  
mean         2099.333529  
std          1542.432736  
min            33.290000  
25%           878.856000  
50%          1828.273366  
75%          2949.298043  
max         13086.964800

In [20]:
#Выведите отдельно интересующую вас колонку и столбец

data['Outlet_Establishment_Year']

0        1999
1        2009
2        1999
3        1998
4        1987
         ... 
14199    1997
14200    2009
14201    2002
14202    2007
14203    2002
Name: Outlet_Establishment_Year, Length: 14204, dtype: int64

## Numpy

In [21]:
import numpy as np

In [25]:
#Создайте вектор (одномерный массив) размера 10, заполненный нулями

arr1 = np.zeros(10)
arr1





array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
#Создайте вектор размера 10, заполненный числом 5.8
arr2 = np.full(10, 5.8)
arr2

array([5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8])

In [31]:
#Создйте массив 3x3x3 со случайными значениями
arr3 = np.random.randint(1,10, size=(3, 3, 3))
arr3

array([[[6, 9, 7],
        [4, 8, 1],
        [9, 5, 6]],

       [[4, 6, 7],
        [4, 9, 8],
        [2, 2, 5]],

       [[6, 8, 8],
        [2, 4, 8],
        [7, 2, 1]]])

In [34]:
#Создайте 8x8 матрицу и заполнить её в шахматном порядке

arr4 = np.ones((8, 8))
arr4[::2, 1::2] =2
arr4[1::2, ::2] =2
arr4

array([[1., 2., 1., 2., 1., 2., 1., 2.],
       [2., 1., 2., 1., 2., 1., 2., 1.],
       [1., 2., 1., 2., 1., 2., 1., 2.],
       [2., 1., 2., 1., 2., 1., 2., 1.],
       [1., 2., 1., 2., 1., 2., 1., 2.],
       [2., 1., 2., 1., 2., 1., 2., 1.],
       [1., 2., 1., 2., 1., 2., 1., 2.],
       [2., 1., 2., 1., 2., 1., 2., 1.]])

In [33]:
#Cоздайте матрицу 4 на 4 и заполните ее произвольными числами (понадобиться в дальйнешем)

arr5 = np.random.randint(1,10, size=(4, 4))
arr5

array([[5, 7, 4, 2],
       [7, 6, 7, 5],
       [9, 8, 1, 9],
       [6, 8, 3, 1]])

## Scipy

In [35]:
from scipy import integrate # Решения интегральных и обычных дифференциальных уравнений
from scipy import linalg # Линейная алгебра

In [37]:
# Возьмите интеграл  ∫10−3sin(x)∗x2dx 

f1 = lambda x:(np.sin(x)*(x**2))
integrate.quad(f1, -3, 10)

(63.57192010714263, 2.1778037844715755e-12)

In [38]:
# Найдите определитель, к матрице из последнего пункта раздела Numpy
linalg.det(arr5)

-346.0000000000002

In [39]:
# обратную матрицу
linalg.inv(arr5)

array([[-1.07514451,  0.30635838, -0.01156069,  0.72254335],
       [ 0.68786127, -0.26589595,  0.02890173, -0.30635838],
       [ 0.16763006,  0.12427746, -0.08959538, -0.15028902],
       [ 0.44508671, -0.08381503,  0.10693642, -0.43352601]])

In [40]:
# собственные значения и собственные векторы
linalg.eig(arr5)

(array([21.97012818+0.j        , -0.63560582+0.j        ,
        -4.16726118+2.72237564j, -4.16726118-2.72237564j]),
 array([[ 0.41815811+0.j        , -0.79507057+0.j        ,
         -0.14392503+0.17064305j, -0.14392503-0.17064305j],
        [ 0.56598324+0.j        ,  0.49596302+0.j        ,
         -0.29441056-0.39471897j, -0.29441056+0.39471897j],
        [ 0.57468895+0.j        ,  0.08264306+0.j        ,
          0.73796565+0.j        ,  0.73796565-0.j        ],
        [ 0.41777911+0.j        ,  0.33919551+0.j        ,
         -0.01807238+0.40344266j, -0.01807238-0.40344266j]]))

## Matplotlib/Seaborn

In [41]:
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import constants

In [46]:
#Нарисуйте график sin(x), подпишите оси, добавьте сетку

lag =0.1
x = np.arange(0.0, 3 * np.pi, lag)
y = np.sin(x)

fig = plt.figure()
plt.plot(x, y)
plt.grid()

plt.title('График sin(x)')
plt.xlabel('X')
plt.ylabel('Y')

Text(0, 0.5, 'Y')

In [49]:
#Нарисуйте график sin(x) и cos(x) на одном subplot'е и на разных, задайте цвета, которые вам больше нравятся

lag =0.1
x = np.arange(0.0, 3 * np.pi, lag)
y1 = np.sin(x)
y2 = np.cos(x)

fig = plt.figure()
plt.plot(x, y1, x, y2)
plt.grid()

plt.title('График sin(x) и cos(x)')
plt.xlabel('X')
plt.ylabel('Y')

Text(0, 0.5, 'Y')

In [62]:
plt.figure(figsize = (20, 5))
lag =0.1
x = np.arange(0.0, 3 * np.pi, lag)
y1 = np.sin(x)
y2 = np.cos(x)

plt.subplot(1, 3, 1)
plt.plot(x, y1, x, y2)
plt.grid()
plt.title('График sin(x) и cos(x)')
plt.xlabel('X')
plt.ylabel('Y')

plt.subplot(1, 3, 2)
plt.plot(x, y1, 'r')
plt.grid()
plt.title('График sin(x)')
plt.xlabel('X')
plt.ylabel('Y')

plt.subplot(1, 3, 3)
plt.plot(x, y2, 'b', '--')
plt.grid()
plt.title('График cos(x)')
plt.xlabel('X')
plt.ylabel('Y')

Text(0, 0.5, 'Y')