### ДЗ. Numpy и Pandas

### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

In [114]:
import pandas as pd

In [191]:
data = pd.read_csv('C:/Users/vkhur/Desktop/Buckkemp Datascience/data.csv')


In [205]:
data.head(20)

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0            FDA15        9.300          Low Fat         0.016047   
1            DRC01        5.920          Regular         0.019278   
2            FDN15       17.500          Low Fat         0.016760   
3            FDX07       19.200          Regular         0.000000   
4            NCD19        8.930          Low Fat         0.000000   
5            FDP36       10.395          Regular         0.000000   
6            FDO10       13.650          Regular         0.012741   
7            FDP10       12.600          Low Fat         0.127470   
8            FDH17       16.200          Regular         0.016687   
9            FDU28       19.200          Regular         0.094450   
10           FDY07       11.800          Low Fat         0.000000   
11           FDA03       18.500          Regular         0.045464   
12           FDX32       15.100          Regular         0.100014   
13           FDS46       17.600          Regular         0.047257   
14           FDF32       16.350          Low Fat         0.068024   
15           FDP49        9.000          Regular         0.069089   
16           NCB42       11.800          Low Fat         0.008596   
17           FDP49        9.000          Regular         0.069196   
18           DRI11       12.600          Low Fat         0.034238   
19           FDU02       13.350          Low Fat         0.102492   

                Item_Type  Item_MRP Outlet_Identifier  \
0                   Dairy  249.8092            OUT049   
1             Soft Drinks   48.2692            OUT018   
2                    Meat  141.6180            OUT049   
3   Fruits and Vegetables  182.0950            OUT010   
4               Household   53.8614            OUT013   
5            Baking Goods   51.4008            OUT018   
6             Snack Foods   57.6588            OUT013   
7             Snack Foods  107.7622            OUT027   
8            Frozen Foods   96.9726            OUT045   
9            Frozen Foods  187.8214            OUT017   
10  Fruits and Vegetables   45.5402            OUT049   
11                  Dairy  144.1102            OUT046   
12  Fruits and Vegetables  145.4786            OUT049   
13            Snack Foods  119.6782            OUT046   
14  Fruits and Vegetables  196.4426            OUT013   
15              Breakfast   56.3614            OUT046   
16     Health and Hygiene  115.3492            OUT018   
17              Breakfast   54.3614            OUT049   
18            Hard Drinks  113.2834            OUT027   
19                  Dairy  230.5352            OUT035   

    Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                        1999      Medium               Tier 1   
1                        2009      Medium               Tier 3   
2                        1999      Medium               Tier 1   
3                        1998         NaN               Tier 3   
4                        1987        High               Tier 3   
5                        2009      Medium               Tier 3   
6                        1987        High               Tier 3   
7                        1985      Medium               Tier 3   
8                        2002         NaN               Tier 2   
9                        2007         NaN               Tier 2   
10                       1999      Medium               Tier 1   
11                       1997       Small               Tier 1   
12                       1999      Medium               Tier 1   
13                       1997       Small               Tier 1   
14                       1987        High               Tier 3   
15                       1997       Small               Tier 1   
16                       2009      Medium               Tier 3   
17                       1999      Medium               Tier 1   
18                       1985      Medium               Tier 3   
19                       2004      

In [141]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                11765 non-null  float64
 2   Item_Fat_Content           14204 non-null  object 
 3   Item_Visibility            14204 non-null  float64
 4   Item_Type                  14204 non-null  object 
 5   Item_MRP                   14204 non-null  float64
 6   Outlet_Identifier          14204 non-null  object 
 7   Outlet_Establishment_Year  14204 non-null  int64  
 8   Outlet_Size                10188 non-null  object 
 9   Outlet_Location_Type       14204 non-null  object 
 10  Outlet_Type                14204 non-null  object 
 11  Item_Outlet_Sales          14204 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.3+ MB


In [193]:
data.isnull().sum()

Item_Identifier                 0
Item_Weight                  2439
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

* Item_Identifier - Идентификатор элемента
* Item_Weight  - Вес товара
* Item_Fat_Content  - Содержание жира
* Item_Visibility - Видимость
* Item_Type  - Тип
* Item_MRP - Item_MRP 
* Outlet_Identifier  - Идентификатор Выхода
* Outlet_Establishment_Year  - выпуск_установка_год
* Outlet_Size  - Размер выхода
* Outlet_Location_Type - Тип размещения
* Outlet_Type - Выходной тип
* Item_Outlet_Sales   -  Распродажи товаров

In [118]:
data.describe()

Item_Weight  Item_Visibility      Item_MRP  Outlet_Establishment_Year  \
count  11765.000000     14204.000000  14204.000000               14204.000000   
mean      12.792854         0.065953    141.004977                1997.830681   
std        4.652502         0.051459     62.086938                   8.371664   
min        4.555000         0.000000     31.290000                1985.000000   
25%        8.710000         0.027036     94.012000                1987.000000   
50%       12.600000         0.054021    142.247000                1999.000000   
75%       16.750000         0.094037    185.855600                2004.000000   
max       21.350000         0.328391    266.888400                2009.000000   

       Item_Outlet_Sales  
count       14204.000000  
mean         2099.333529  
std          1542.432736  
min            33.290000  
25%           878.856000  
50%          1828.273366  
75%          2949.298043  
max         13086.964800

In [119]:
data.corr()

Item_Weight  Item_Visibility  Item_MRP  \
Item_Weight                   1.000000        -0.015901  0.036236   
Item_Visibility              -0.015901         1.000000 -0.006351   
Item_MRP                      0.036236        -0.006351  1.000000   
Outlet_Establishment_Year     0.000645        -0.083678  0.000141   
Item_Outlet_Sales             0.026816        -0.134118  0.602297   

                           Outlet_Establishment_Year  Item_Outlet_Sales  
Item_Weight                                 0.000645           0.026816  
Item_Visibility                            -0.083678          -0.134118  
Item_MRP                                    0.000141           0.602297  
Outlet_Establishment_Year                   1.000000          -0.054176  
Item_Outlet_Sales                          -0.054176           1.000000

In [212]:
data['Item_Identifier'].unique()

array(['FDA15', 'DRC01', 'FDN15', ..., 'NCF55', 'NCW30', 'NCW05'],
      dtype=object)

In [213]:
data['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular'], dtype=object)

In [214]:
data['Item_Fat_Content'] = data['Item_Fat_Content'].replace({'low fat': 'Low Fat'})
data['Item_Fat_Content'] = data['Item_Fat_Content'].replace({'LF': 'Low Fat'})
data['Item_Fat_Content'] = data['Item_Fat_Content'].replace({'reg': 'Regular'})
data['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular'], dtype=object)

In [215]:
data['Item_Type'].unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

In [216]:
data['Outlet_Identifier'].unique()

array(['OUT049', 'OUT018', 'OUT010', 'OUT013', 'OUT027', 'OUT045',
       'OUT017', 'OUT046', 'OUT035', 'OUT019'], dtype=object)

In [217]:
data['Outlet_Size'].unique()

array(['Medium', nan, 'High', 'Small'], dtype=object)

In [180]:
data.replace(
    {'Outlet_Size':
     {'NaN': data['Outlet_Size'].mode()[0]}
    },
    inplace=True)

In [218]:
data[data['Outlet_Size'] == 'NaN'].head()

Empty DataFrame
Columns: [Item_Identifier, Item_Weight, Item_Fat_Content, Item_Visibility, Item_Type, Item_MRP, Outlet_Identifier, Outlet_Establishment_Year, Outlet_Size, Outlet_Location_Type, Outlet_Type, Item_Outlet_Sales]
Index: []

In [219]:
median = data['Item_Weight'].median() # Заменяю пропуски на медиану
data['Item_Weight'].fillna(median, inplace=True)

In [220]:
data.isna().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [221]:
data['Outlet_Size'] = data['Outlet_Size'].replace({'NaN': 'Medium'})

In [222]:
data['Outlet_Size'].isna().sum()

4016

In [223]:
data.groupby(['Outlet_Size']).count()

Item_Identifier  Item_Weight  Item_Fat_Content  Item_Visibility  \
Outlet_Size                                                                    
High                    1553         1553              1553             1553   
Medium                  4655         4655              4655             4655   
Small                   3980         3980              3980             3980   

             Item_Type  Item_MRP  Outlet_Identifier  \
Outlet_Size                                           
High              1553      1553               1553   
Medium            4655      4655               4655   
Small             3980      3980               3980   

             Outlet_Establishment_Year  Outlet_Location_Type  Outlet_Type  \
Outlet_Size                                                                 
High                              1553                  1553         1553   
Medium                            4655                  4655         4655   
Small                             3980                  3980         3980   

             Item_Outlet_Sales  
Outlet_Size                     
High                      1553  
Medium                    4655  
Small                     3980

In [224]:
data['Outlet_Location_Type'].unique()

array(['Tier 1', 'Tier 3', 'Tier 2'], dtype=object)

In [225]:
data['Outlet_Type'].unique()

array(['Supermarket Type1', 'Supermarket Type2', 'Grocery Store',
       'Supermarket Type3'], dtype=object)

# 1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [3]:
import numpy as np

In [5]:
A = np.array([[1, -2, 4],[2, 0, -1]])
B = np.array([[5, 2, 3],[4, 6, 2]])

array([[5, 2, 3],
       [4, 6, 2]])

In [7]:
A+B, A-B

(array([[6, 0, 7],
        [6, 6, 1]]),
 array([[-4, -4,  1],
        [-2, -6, -3]]))

# 2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [66]:
A = np.array([[1, 2],[2, -1],[3, 0,]])
B = np.array([[-1, 1],[1, 2],[0, 0,]])

array([[-1,  1],
       [ 1,  2],
       [ 0,  0]])

In [67]:
С = A - B*3
C

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

# 3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [69]:
A = np.array([[1, -1],[2, 0],[3, 0,]])
B = np.array([[1, 1],[2, 0,]])
C = A.dot(B)
C

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

# 4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [57]:
A = np.array([[6, -1, 4],[2, 1, 10],[8, 0, 2]])
A

array([[ 6, -1,  4],
       [ 2,  1, 10],
       [ 8,  0,  2]])

In [58]:
np.linalg.det(A)

-95.99999999999999

# 5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [71]:
A = np.array([[3, 3, -1],[4, 1, 3],[1, -2, -2]])
A

array([[ 3,  3, -1],
       [ 4,  1,  3],
       [ 1, -2, -2]])

In [74]:
A_inv = np.linalg.inv(A)
A_Inv2 = np.linalg.inv(A_inv)
A_Inv2

array([[ 3.,  3., -1.],
       [ 4.,  1.,  3.],
       [ 1., -2., -2.]])